[build]
  command = "yarn build"
  publish = "out"
  functions = "out_functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
REACT_APP_SUBNUB_ENV = "prod"
